Repository ahmadawais/corona-cli, pull requests merged in 2020-03, with the labels that each got.

#40 📦 NEW: Reverse order of output
  index.js
  readme.md
  utils/cli.js
  utils/getCountries.js
  utils/getStates.js
Labels: 📦 NEW

#17 📦 NEW: limit functionality to cli
  index.js
  readme.md
  utils/cli.js
  utils/getCountries.js
  utils/getStates.js
Labels: 📦 NEW

#41 📦 NEW: NonVerbose
  index.js
  utils/cli.js
  utils/init.js
  utils/table.js
  utils/theEnd.js
Labels: 👌 IMPROVE, 📦 NEW

#52 🐛 FIX: Minimal Flag - Bug Fix - Default
  utils/cli.js
Labels: 👌 IMPROVE
